### ISSUE TITLE
Compilation bug with i2c version 4.2 gcc 10 on Linux mx 21

### ISSUE THREAD

**Issue by ewe2** [johnwinans/2065-Z80-programmer#1]
Here's the error, nothing serious, just a nuisance really.
```
$ make
cc -Wall -Werror    flash.c  -li2c -o flash
flash.c: In function ‘main’:
flash.c:535:50: error: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Werror=format=]
  535 |    printf("program file is too big, limiting to %d bytes\n", sizeof(buf));
      |                                                 ~^           ~~~~~~~~~~~
      |                                                  |           |
      |                                                  int         long unsigned int
      |                                                 %ld
cc1: all warnings being treated as errors
make: *** [<builtin>: flash] Error 1
```
I know most people are not Linux nerds and this will probably not apply to Windows users whose systems won't treat this as an error, but I thought it worth mentioning anyway, I can just fix it on my local copy with a preprocessor kludge or something.

**Comment by johnwinans** [comment]
I suspect I have a 32-bit OS on my PI and you have a 64-bit version.
I'll cast it.

**Comment by johnwinans** [comment]
Try fac3bd9deb04e0311b4795c2268ae3e6526cb988 and let me know if that works on your install.

**Comment by ewe2** [comment]
Oh of course that makes sense. I was just testing compilation and didn't think about a Pi compilation. However I can also do this on my Potato whiich *does* run a 64bit OS and would have an issue here (although a Potato is massive overkill for the job  haha)..
